

type UserXpActionsPointsKeys =
    "ACCOUNT_LINE_RULE_CREATED" |
    "ACCOUNT_LINE_OPERATION_CREATED" |
    "ACCOUNT_LINE_OPERATION_VALIDATED" |
    "ACCOUNT_RECURRING_EXPENSE_CREATED";

const UserXpActionsPoints: { [key in UserXpActionsPointsKeys]: number } = {
    ACCOUNT_LINE_RULE_CREATED: 10,
    ACCOUNT_LINE_OPERATION_CREATED: 5,
    ACCOUNT_LINE_OPERATION_VALIDATED: 20,
    ACCOUNT_RECURRING_EXPENSE_CREATED: 100
};

export { UserXpActionsPoints, UserXpActionsPointsKeys };